# Generated by Django 4.1.1 on 2023-01-29 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('group_id', models.ForeignKey(blank=True, help_text='Assign to a team', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter project title', max_length=100, verbose_name='Project title')),
                ('description', models.TextField(help_text='Enter project description', max_length=2000, verbose_name='Description')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='Requested finish date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.BooleanField(default=False, verbose_name='Completed')),
                ('group_id', models.ForeignKey(blank=True, help_text='Assign to a team', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Team role', max_length=200, verbose_name='Role in a team')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='Enter Task role', max_length=200, null=True, verbose_name='Task title')),
                ('description', models.TextField(blank=True, help_text='Enter task description', max_length=2000, null=True, verbose_name='Description')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='Requested finish date')),
                ('completed_on', models.BooleanField(default=False, verbose_name='Completed')),
                ('assign_employees', models.OneToOneField(help_text='Select employees to task', on_delete=django.db.models.deletion.CASCADE, to='taskman.employee')),
                ('project_id', models.ForeignKey(blank=True, help_text='Assign to a task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskman.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000, verbose_name='Comment')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskman.taskinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Number of tasks assigned')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taskman.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team_role',
            field=models.ForeignKey(blank=True, help_text='Assign a position', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskman.teamrole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
