# Generated by Django 4.1.1 on 2023-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee_req',
            field=models.IntegerField(default=0, verbose_name='Number of employees expected'),
        ),
    ]
