# Generated by Django 4.1.1 on 2023-01-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0002_project_employee_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='assign_employees',
            field=models.ForeignKey(help_text='Select employees to task', on_delete=django.db.models.deletion.CASCADE, to='taskman.employee'),
        ),
    ]
