# Generated by Django 4.1.1 on 2023-01-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0004_projectcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWork',
        ),
    ]
