# Generated by Django 4.1.1 on 2023-01-30 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0005_delete_employeework'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Number of tasks assigned'),
        ),
    ]
