# Generated by Django 4.1.1 on 2023-01-31 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0006_employee_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_number',
            field=models.IntegerField(default=0, verbose_name='Number of tasks assigned'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employee_req',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of employees expected'),
        ),
    ]
